global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'pismo-app'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
